version: '3.8'
services:
    database:
        build:
            context: .
            dockerfile: docker/mysql/Dockerfile
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        command: --default-authentication-plugin=mysql_native_password
        restart: unless-stopped
        volumes:
            - ./docker/data:/usr/data
        ports:
            - 3306:3306
    web:
        build:
            context: .
            dockerfile: docker/apache/Dockerfile
            args:
                uid: ${UID}
        environment:
            - APACHE_RUN_USER=#${UID}
            - APACHE_RUN_GROUP=#${UID}
        restart: unless-stopped
        volumes:
            - ./src:/var/www/html
            - ./docker/apache/log:/var/log/apache2
        ports:
            - 80:80
        depends_on:
            - database
        links:
            - database